<a href="https://colab.research.google.com/github/26wh5a0538-create/NASSCOM/blob/main/NumPy_Exercise.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [5]:
import numpy as np

print("\n--- Task 1: Array Creation Shortcuts ---")

arr1_1 = np.arange(100)

arr1_2 = np.ones((3, 3))
arr1_3 = np.full((2, 4), 7)

arr1_4 = np.random.randint(10, 51, size=(5, 5))

print("arr1_1:", arr1_1)
print("\narr1_2:\n", arr1_2)
print("\narr1_3:\n", arr1_3)
print("\narr1_4:\n", arr1_4)


--- Task 1: Array Creation Shortcuts ---
arr1_1: [ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23
 24 25 26 27 28 29 30 31 32 33 34 35 36 37 38 39 40 41 42 43 44 45 46 47
 48 49 50 51 52 53 54 55 56 57 58 59 60 61 62 63 64 65 66 67 68 69 70 71
 72 73 74 75 76 77 78 79 80 81 82 83 84 85 86 87 88 89 90 91 92 93 94 95
 96 97 98 99]

arr1_2:
 [[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]

arr1_3:
 [[7 7 7 7]
 [7 7 7 7]]

arr1_4:
 [[44 30 22 47 14]
 [28 37 16 40 31]
 [44 32 23 46 26]
 [24 37 22 41 18]
 [46 21 19 27 12]]


In [6]:

print("\n--- Task 2: Indexing and Slicing with Arrays ---")

data = np.array([[10, 20, 30, 40],
                 [50, 60, 70, 80],
                 [90, 100, 110, 120],
                 [130, 140, 150, 160]])
 3
val2_1 = data[2, 3]

row2_2 = data[0]

col2_3 = data[:, -1]

sub_arr2_4 = data[1:3, 0:2]

filtered_elements2_5 = data[data > 100]

print("val2_1:", val2_1)
print("row2_2:", row2_2)
print("col2_3:", col2_3)
print("sub_arr2_4:\n", sub_arr2_4)
print("filtered_elements2_5:", filtered_elements2_5)


--- Task 2: Indexing and Slicing with Arrays ---
val2_1: 120
row2_2: [10 20 30 40]
col2_3: [ 40  80 120 160]
sub_arr2_4:
 [[ 50  60]
 [ 90 100]]
filtered_elements2_5: [110 120 130 140 150 160]


In [7]:

val2_1 = data[2, 3]

row2_2 = data[0]

col2_3 = data[:, -1]

sub_arr2_4 = data[1:3, 0:2]

filtered_elements2_5 = data[data > 100]

print("val2_1:", val2_1)
print("row2_2:", row2_2)
print("col2_3:", col2_3)
print("sub_arr2_4:\n", sub_arr2_4)
print("filtered_elements2_5:", filtered_elements2_5)

val2_1: 120
row2_2: [10 20 30 40]
col2_3: [ 40  80 120 160]
sub_arr2_4:
 [[ 50  60]
 [ 90 100]]
filtered_elements2_5: [110 120 130 140 150 160]


In [8]:

print("\n--- Task 3: Conditional Operations ---")

arr3_1 = np.random.randint(1, 21, size=(4, 5))

arr3_2 = np.where(arr3_1 < 10, 0, arr3_1)

even_count3_3 = np.count_nonzero(arr3_1 % 2 == 0)

print("arr3_1:")
print(arr3_1)

print("\narr3_2:")
print(arr3_2)

print("\neven_count3_3:", even_count3_3)


--- Task 3: Conditional Operations ---
arr3_1:
[[14  1 18  1  7]
 [ 9 19 15 15  9]
 [19  8  1 17  5]
 [18 16 20 18 16]]

arr3_2:
[[14  0 18  0  0]
 [ 0 19 15 15  0]
 [19  0  0 17  0]
 [18 16 20 18 16]]

even_count3_3: 8


In [10]:

print("\n--- Task 4: Aggregation Functions ---")

arr4_1 = np.array([[10, 5, 12],
                   [3, 8, 15],
                   [20, 7, 4]])

sum4_1 = np.sum(arr4_1)

mean_cols4_2 = np.mean(arr4_1, axis=0)

max_rows4_3 = np.max(arr4_1, axis=1)

std4_4 = np.std(arr4_1)

print("sum4_1:", sum4_1)
print("mean_cols4_2:", mean_cols4_2)
print("max_rows4_3:", max_rows4_3)
print("std4_4:", std4_4)


--- Task 4: Aggregation Functions ---
sum4_1: 84
mean_cols4_2: [11.          6.66666667 10.33333333]
max_rows4_3: [12 15 20]
std4_4: 5.2493385826745405


In [11]:

print("\n--- Task 5: Reshaping and Flattening ---")

arr5_1 = np.arange(24)
reshaped_arr5_2 = arr5_1.reshape(4, 6)


reshaped_arr5_3 = arr5_1.reshape(2, 3, 4)

flattened_arr5_4 = reshaped_arr5_2.ravel()


flattened_arr5_4_flatten = reshaped_arr5_2.flatten()

print("arr5_1:")
print(arr5_1)

print("\nreshaped_arr5_2:")
print(reshaped_arr5_2)

print("\nreshaped_arr5_3:")
print(reshaped_arr5_3)

print("\nflattened_arr5_4:")
print(flattened_arr5_4)

print("\nUsing flatten():")
print(flattened_arr5_4_flatten)


--- Task 5: Reshaping and Flattening ---
arr5_1:
[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23]

reshaped_arr5_2:
[[ 0  1  2  3  4  5]
 [ 6  7  8  9 10 11]
 [12 13 14 15 16 17]
 [18 19 20 21 22 23]]

reshaped_arr5_3:
[[[ 0  1  2  3]
  [ 4  5  6  7]
  [ 8  9 10 11]]

 [[12 13 14 15]
  [16 17 18 19]
  [20 21 22 23]]]

flattened_arr5_4:
[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23]

Using flatten():
[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23]


In [12]:

print("\n--- Task 6: Broadcasting ---")

arr6_1 = np.array([[1, 2, 3],
                   [4, 5, 6],
                   [7, 8, 9]])

scalar = 10
vector = np.array([100, 200, 300])

result6_1 = arr6_1 + scalar

result6_2 = arr6_1 + vector

print("result6_1:")
print(result6_1)

print("\nresult6_2:")
print(result6_2)


--- Task 6: Broadcasting ---
result6_1:
[[11 12 13]
 [14 15 16]
 [17 18 19]]

result6_2:
[[101 202 303]
 [104 205 306]
 [107 208 309]]


In [13]:

print("\n--- Task 7: Copying vs. Viewing Arrays ---")

original_arr7 = np.array([1, 2, 3, 4, 5])

view_arr7 = original_arr7[:]
view_arr7[0] = 99

print("view_arr7:")
print(view_arr7)

print("original_arr7 after modifying view:")
print(original_arr7)

copy_arr7 = original_arr7.copy()
copy_arr7[-1] = 0

print("\ncopy_arr7:")
print(copy_arr7)

print("original_arr7 after modifying copy:")
print(original_arr7)


--- Task 7: Copying vs. Viewing Arrays ---
view_arr7:
[99  2  3  4  5]
original_arr7 after modifying view:
[99  2  3  4  5]

copy_arr7:
[99  2  3  4  0]
original_arr7 after modifying copy:
[99  2  3  4  5]


In [18]:

print("\n--- Task 9: Sorting and Searching ---")

arr9_1 = np.array([5, 2, 8, 1, 9, 4, 7, 3, 6])

arr9_2d = np.array([[30, 20, 10],
                    [60, 50, 40],
                    [90, 80, 70]])

sorted_arr9_1 = np.sort(arr9_1)

sorted_cols9_2 = np.sort(arr9_2d, axis=0)

idx9_3 = np.where(arr9_1 == 9)

max_idx9_4 = np.argmax(arr9_1)

print("sorted_arr9_1:", sorted_arr9_1)
print("\nsorted_cols9_2:")
print(sorted_cols9_2)
print("\nidx9_3:", idx9_3)
print("\nmax_idx9_4:", max_idx9_4)


--- Task 9: Sorting and Searching ---
sorted_arr9_1: [1 2 3 4 5 6 7 8 9]

sorted_cols9_2:
[[30 20 10]
 [60 50 40]
 [90 80 70]]

idx9_3: (array([4]),)

max_idx9_4: 4
