<a href="https://colab.research.google.com/github/26wh5a0538-create/NASSCOM/blob/main/week_Pandas_Exercise.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [30]:
import pandas as pd
import numpy as np

print("--- Intermediate Pandas Exercise ---")
print("Complete each task by writing the requested Pandas code.")
print("------------------------------------")

print("\n--- Task 1: Basic Pandas Functions and Converting Arrays to DataFrames ---")

s1_1 = pd.Series([10, 20, 30, 40, 50])
print("\ns1_1:")
print(s1_1)

np_array1_2 = np.random.randint(1, 101, size=(3, 4))
print("\nnp_array1_2:")
print(np_array1_2)

df1_3 = pd.DataFrame(np_array1_2, columns=['A', 'B', 'C', 'D'])
print("\ndf1_3:")
print(df1_3)

--- Intermediate Pandas Exercise ---
Complete each task by writing the requested Pandas code.
------------------------------------

--- Task 1: Basic Pandas Functions and Converting Arrays to DataFrames ---

s1_1:
0    10
1    20
2    30
3    40
4    50
dtype: int64

np_array1_2:
[[41 50 16 54]
 [25 84 69 71]
 [61 62 20 40]]

df1_3:
    A   B   C   D
0  41  50  16  54
1  25  84  69  71
2  61  62  20  40


In [31]:

print("\n--- Task 2: Synthetic Data Generation for Practice ---")

np.random.seed(42)

dates = pd.date_range(start='2023-01-01', end='2023-04-09', periods=100)


df_sales = pd.DataFrame({
    'Date': dates,
    'Region': np.random.choice(['East', 'West', 'North', 'South'], size=100),
    'Product': np.random.choice(['Laptop', 'Mouse', 'Keyboard', 'Monitor'], size=100),
    'Sales': np.random.randint(100, 1001, size=100),
    'Quantity': np.random.randint(1, 11, size=100)
})

sales_nan_indices = np.random.choice(df_sales.index, size=5, replace=False)
df_sales.loc[sales_nan_indices, 'Sales'] = np.nan

quantity_nan_indices = np.random.choice(df_sales.index, size=3, replace=False)
df_sales.loc[quantity_nan_indices, 'Quantity'] = np.nan

print(df_sales)


--- Task 2: Synthetic Data Generation for Practice ---
                            Date Region   Product  Sales  Quantity
0  2023-01-01 00:00:00.000000000  North  Keyboard  674.0       7.0
1  2023-01-01 23:45:27.272727272  South     Mouse  963.0       4.0
2  2023-01-02 23:30:54.545454545   East     Mouse    NaN       7.0
3  2023-01-03 23:16:21.818181818  North   Monitor  340.0       8.0
4  2023-01-04 23:01:49.090909090  North     Mouse  663.0       1.0
..                           ...    ...       ...    ...       ...
95 2023-04-05 00:58:10.909090910   West     Mouse  152.0       6.0
96 2023-04-06 00:43:38.181818182   West     Mouse  783.0       8.0
97 2023-04-07 00:29:05.454545455  South   Monitor  829.0       2.0
98 2023-04-08 00:14:32.727272728   West    Laptop  771.0       5.0
99 2023-04-09 00:00:00.000000000   East  Keyboard  809.0       1.0

[100 rows x 5 columns]


In [32]:

print("\n--- Task 3: Indexing and Slicing in DataFrames ---")

df3_1 = df_sales[['Region', 'Sales']]
print("\ndf3_1:")
print(df3_1)

df3_2 = df_sales[df_sales['Product'] == 'Laptop']
print("\ndf3_2:")
print(df3_2)

df3_3 = df_sales[(df_sales['Region'] == 'East') & (df_sales['Sales'] > 500)]
print("\ndf3_3:")
print(df3_3)

monitor_rows = df_sales[df_sales['Product'] == 'Monitor']
val3_4 = df_sales.loc[monitor_rows.index[0], 'Sales']

print("\nval3_4:")
print(val3_4)


--- Task 3: Indexing and Slicing in DataFrames ---

df3_1:
   Region  Sales
0   North  674.0
1   South  963.0
2    East    NaN
3   North  340.0
4   North  663.0
..    ...    ...
95   West  152.0
96   West  783.0
97  South  829.0
98   West  771.0
99   East  809.0

[100 rows x 2 columns]

df3_2:
                            Date Region Product  Sales  Quantity
16 2023-01-16 20:07:16.363636363  South  Laptop  624.0       4.0
19 2023-01-19 19:23:38.181818182  North  Laptop  798.0      10.0
21 2023-01-21 18:54:32.727272727   East  Laptop  185.0       3.0
24 2023-01-24 18:10:54.545454545  South  Laptop  781.0       4.0
27 2023-01-27 17:27:16.363636364   West  Laptop  745.0       8.0
31 2023-01-31 16:29:05.454545455   East  Laptop  655.0       1.0
32 2023-02-01 16:14:32.727272727  South  Laptop  439.0       9.0
33 2023-02-02 16:00:00.000000000   West  Laptop  897.0       9.0
35 2023-02-04 15:30:54.545454545   East  Laptop  739.0       7.0
36 2023-02-05 15:16:21.818181818  South  Laptop  605.0

In [33]:

print("\n--- Task 4: Data Cleaning (Handling Missing Values) ---")

missing_counts4_1 = df_sales.isnull().sum()
print("Missing values:")
print(missing_counts4_1)

df4_2_filled = df_sales.copy()
df4_2_filled['Sales'] = df4_2_filled['Sales'].fillna(df4_2_filled['Sales'].mean())

df4_3_dropped = df_sales.dropna()

print("\nFilled DataFrame:")
print(df4_2_filled)

print("\nDataFrame after dropping missing values:")
print(df4_3_dropped)


--- Task 4: Data Cleaning (Handling Missing Values) ---
Missing values:
Date        0
Region      0
Product     0
Sales       5
Quantity    3
dtype: int64

Filled DataFrame:
                            Date Region   Product       Sales  Quantity
0  2023-01-01 00:00:00.000000000  North  Keyboard  674.000000       7.0
1  2023-01-01 23:45:27.272727272  South     Mouse  963.000000       4.0
2  2023-01-02 23:30:54.545454545   East     Mouse  590.147368       7.0
3  2023-01-03 23:16:21.818181818  North   Monitor  340.000000       8.0
4  2023-01-04 23:01:49.090909090  North     Mouse  663.000000       1.0
..                           ...    ...       ...         ...       ...
95 2023-04-05 00:58:10.909090910   West     Mouse  152.000000       6.0
96 2023-04-06 00:43:38.181818182   West     Mouse  783.000000       8.0
97 2023-04-07 00:29:05.454545455  South   Monitor  829.000000       2.0
98 2023-04-08 00:14:32.727272728   West    Laptop  771.000000       5.0
99 2023-04-09 00:00:00.000000000 

In [34]:

print("\n--- Task 5: Data Manipulation (Columns, Sorting, Grouping) ---")

df_sales['Total_Revenue'] = df_sales['Sales'] * df_sales['Quantity']

df5_2_sorted = df_sales.sort_values(by=['Date', 'Sales'], ascending=[True, False])

df5_3_grouped_region = df_sales.groupby('Region')[['Sales', 'Quantity']].sum()

df5_4_grouped_product = df_sales.groupby('Product')['Sales'].mean()

print("\nSorted DataFrame:")
print(df5_2_sorted)

print("\nGrouped by Region:")
print(df5_3_grouped_region)

print("\nAverage Sales by Product:")
print(df5_4_grouped_product)


--- Task 5: Data Manipulation (Columns, Sorting, Grouping) ---

Sorted DataFrame:
                            Date Region   Product  Sales  Quantity  \
0  2023-01-01 00:00:00.000000000  North  Keyboard  674.0       7.0   
1  2023-01-01 23:45:27.272727272  South     Mouse  963.0       4.0   
2  2023-01-02 23:30:54.545454545   East     Mouse    NaN       7.0   
3  2023-01-03 23:16:21.818181818  North   Monitor  340.0       8.0   
4  2023-01-04 23:01:49.090909090  North     Mouse  663.0       1.0   
..                           ...    ...       ...    ...       ...   
95 2023-04-05 00:58:10.909090910   West     Mouse  152.0       6.0   
96 2023-04-06 00:43:38.181818182   West     Mouse  783.0       8.0   
97 2023-04-07 00:29:05.454545455  South   Monitor  829.0       2.0   
98 2023-04-08 00:14:32.727272728   West    Laptop  771.0       5.0   
99 2023-04-09 00:00:00.000000000   East  Keyboard  809.0       1.0   

    Total_Revenue  
0          4718.0  
1          3852.0  
2             Na